lock-version = "1.0"
environments = ["python_version == '3.10' and platform_machine == 'x86_64'"]

[[packages]]
name = "transformers"
version = "4.40.1"
sha256 = "9d5ee0c8142a60501faf9e49a0b42f8e9cb8611823bce4f195a9325a6816337e"

[[vcs]]
name = "dlimp"
repository = "https://github.com/moojink/dlimp_openvla.git"
revision = "040105d256bd28866cc6620621a3d5f7b6b91b46"
