name: openvla
channels:
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bzip2=1.0.8
  - ca-certificates=2026.3.19
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.9.1
  - cuda-compiler=12.9.1
  - cuda-crt-dev_linux-64=12.9.86
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart-dev=12.9.79
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-cupti-dev=12.9.79
  - cuda-cuxxfilt=12.9.82
  - cuda-documentation=12.4.127
  - cuda-driver-dev=12.9.79
  - cuda-driver-dev_linux-64=12.9.79
  - cuda-gdb=12.9.79
  - cuda-libraries=12.9.1
  - cuda-libraries-dev=12.9.1
  - cuda-libraries-static=12.9.1
  - cuda-nsight=12.9.79
  - cuda-nvcc=12.9.86
  - cuda-nvcc-dev_linux-64=12.9.86
  - cuda-nvcc-impl=12.9.86
  - cuda-nvcc-tools=12.9.86
  - cuda-nvcc_linux-64=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvml-dev=12.9.79
  - cuda-nvprof=12.9.79
  - cuda-nvprune=12.9.82
  - cuda-nvrtc=12.9.86
  - cuda-nvrtc-dev=12.9.86
  - cuda-nvrtc-static=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-dev_linux-64=12.9.86
  - cuda-nvvm-impl=12.9.86
  - cuda-nvvm-tools=12.9.86
  - cuda-nvvp=12.9.79
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-sanitizer-api=12.9.79
  - cuda-toolkit=12.1.1
  - cuda-tools=12.9.1
  - cuda-version=12.9
  - cuda-visual-tools=12.9.1
  - dbus=1.16.2
  - expat=2.7.5
  - fontconfig=2.15.0
  - freetype=2.14.1
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gds-tools=1.14.1.1
  - gmp=6.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - icu=73.1
  - kernel-headers_linux-64=4.18.0
  - ld_impl_linux-64=2.44
  - libcublas=12.9.1.4
  - libcublas-dev=12.9.1.4
  - libcublas-static=12.9.1.4
  - libcufft=11.4.1.4
  - libcufft-dev=11.4.1.4
  - libcufft-static=11.4.1.4
  - libcufile=1.14.1.1
  - libcufile-dev=1.14.1.1
  - libcufile-static=1.14.1.1
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurand-static=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusolver-dev=11.7.5.82
  - libcusolver-static=11.7.5.82
  - libcusparse=12.5.10.65
  - libcusparse-dev=12.5.10.65
  - libcusparse-static=12.5.10.65
  - libexpat=2.7.5
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libiconv=1.18
  - libnpp=12.4.1.87
  - libnpp-dev=12.4.1.87
  - libnpp-static=12.4.1.87
  - libnsl=2.0.0
  - libnvfatbin=12.9.82
  - libnvfatbin-dev=12.9.82
  - libnvfatbin-static=12.9.82
  - libnvjitlink=12.9.86
  - libnvjitlink-dev=12.9.86
  - libnvjitlink-static=12.9.86
  - libnvjpeg=12.4.0.76
  - libnvjpeg-dev=12.4.0.76
  - libnvjpeg-static=12.4.0.76
  - libnvptxcompiler-dev=12.9.86
  - libnvptxcompiler-dev_linux-64=12.9.86
  - libnvvm-samples=12.1.105
  - libpng=1.6.56
  - libsanitizer=14.3.0
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - ncurses=6.5
  - nsight-compute=2025.2.1.3
  - nspr=4.37
  - nss=3.121
  - ocl-icd=2.3.3
  - opencl-headers=2025.07.22
  - openssl=3.5.5
  - packaging=26.0
  - pcre2=10.46
  - pip=26.0.1
  - pthread-stubs=0.3
  - python=3.10.20
  - readline=8.3
  - setuptools=82.0.1
  - sqlite=3.51.2
  - sysroot_linux-64=2.28
  - tk=8.6.15
  - tzdata=2026a
  - wheel=0.46.3
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - zlib=1.3.1
  - pip:
      - absl-py==2.5.0
      - accelerate==0.30.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.13.0
      - array-record==0.8.1
      - astunparse==1.6.3
      - attrs==26.1.0
      - bitsandbytes==0.43.1
      - certifi==2026.2.25
      - cffi==2.1.0
      - charset-normalizer==3.4.7
      - click==8.3.2
      - contourpy==1.3.2
      - cryptography==49.0.0
      - cycler==0.12.1
      - dlimp==0.0.1
      - dm-tree==0.1.10
      - draccus==0.8.0
      - einops==0.8.2
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - fastapi==0.135.3
      - filelock==3.25.2
      - flash-attn==2.5.5
      - flatbuffers==25.12.19
      - fonttools==4.63.0
      - fsspec==2026.2.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.51
      - google-auth==2.56.0
      - google-auth-oauthlib==1.4.0
      - google-pasta==0.2.0
      - grpcio==1.82.1
      - h11==0.16.0
      - h5py==3.16.0
      - hf-xet==1.4.3
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - idna==3.11
      - importlib-resources==7.1.0
      - jinja2==3.1.6
      - json-numpy==2.1.1
      - jsonlines==4.0.0
      - keras==2.15.0
      - kiwisolver==1.5.0
      - libclang==18.1.1
      - markdown==3.10.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.9
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - openexr==3.4.13
      - openvla==0.0.3
      - opt-einsum==3.4.0
      - peft==0.11.1
      - pillow==12.1.1
      - platformdirs==4.10.0
      - promise==2.3
      - protobuf==4.25.9
      - psutil==7.2.2
      - pyasn1==0.6.4
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.20.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - regex==2026.4.4
      - requests==2.33.1
      - requests-oauthlib==2.0.0
      - rich==14.3.3
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.65.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.3
      - starlette==1.0.0
      - sympy==1.13.1
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.21.0
      - termcolor==3.3.0
      - timm==0.9.10
      - tokenizers==0.19.1
      - toml==0.10.2
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tqdm==4.67.3
      - transformers==4.40.1
      - trimesh==4.12.2
      - triton==2.2.0
      - typeguard==2.13.3
      - typer==0.24.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uvicorn==0.44.0
      - wandb==0.28.0
      - werkzeug==3.1.8
      - wrapt==1.14.2
      - zipp==4.1.0
